### ISSUE TITLE
There is an error when array of primitive generation.

### ISSUE THREAD

**Issue by mathter** [mathter/genthz#31]
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [Ljava.lang.Object; ([B and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at org.genthz.dasha.context.DashaContextFactory.byArray(DashaContextFactory.java:129)
	at org.genthz.function.DefaultArrayFiller.fill(DefaultArrayFiller.java:39)
	at org.genthz.dasha.DashaObjectFactory.processNew(DashaObjectFactory.java:97)
	... 69 more

**Comment by mathter** [comment]
Fixed
